#!/bin/bash -x

#curl http://rndmweb.hell/parted.txt -o parted.txt
curl https://gitlab.com/insanitywholesale/installscripts/raw/master/parted.txt -o parted.txt
pacman -Syy parted --noconfirm
dd if=/dev/zero of=/dev/sda bs=512 count=1 conv=notrunc
parted -a optimal /dev/sda < parted.txt
mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2
#replace with swapfile creation...
#mkswap /dev/sda3
#swapon /dev/sda3
#...at some point
mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
basestrap /mnt base base-devel runit efibootmgr grub vim
fstabgen -U /mnt >> /mnt/etc/fstab
artools-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Athens /etc/localtime
artools-chroot /mnt hwclock --systohc
artools-chroot /mnt echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
artools-chroot /mnt echo 'LANG=en_US.UTF-8' > /etc/locale.conf
artools-chroot /mnt locale-gen
artools-chroot /mnt echo '127.0.0.1   localhost' > /etc/hosts
artools-chroot /mnt echo '::1     localhost' >> /etc/hosts
artools-chroot /mnt echo '127.0.1.1   localhost.localdomain    localhost' >> /etc/hosts
artools-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=artix --removable
artools-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
echo 'please run the following command to set a root password: passwd --root /mnt root'
