#!/bin/bash -x

source /etc/profile
export PS1="(chroot) ${PS1}"
mount /dev/sda1 /boot
mkdir /etc/portage/repos.conf
curl -o /etc/portage/repos.conf/gentoo.conf https://gitlab.com/insanitywholesale/dotfiles/raw/master/gentoo/gentoo.conf
emerge-webrsync
eselect profile list
read PROFILE
eselect profile set $PROFILE
echo "Europe/Athens" > /etc/timezone
emerge --config sys-libs/timezone-data
echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
echo 'en_US ISO-8859-1' >> /etc/locale.gen
locale-gen
eselect locale list
echo "enter locale number"
read LOCALE
eselect locale set $LOCALE
env-update && source /etc/profile && export PS1="(chroot) $PS1"
mkdir /etc/portage/patches
echo "app-admin/rsyslog gnutls openssl" > /etc/portage/package.use/rsyslog
emerge -v --noreplace netifrc
emerge -v linux-firmware gentoo-sources sudo pciutils grub vim tmux cronie rsyslog netifrc layman genkernel
(cd /etc/init.d && ln -s net.lo net.eth0)
rc-update add net.eth0 default
rc-update add sshd default
rc-update add cronie default
rc-update add rsyslog default
echo 'virtgent' > /etc/hostname
echo 'hostname="virtgent"' > /etc/conf.d/hostname
echo 'dns_domain_lo="hell"' > /etc/conf.d/net
echo 'config_eth0="dhcp"' >> /etc/conf.d/net
echo '127.0.0.1  virtgent.hell virtgent localhost' > /etc/hosts
echo '#::1     localhost' >> /etc/hosts
curl -o https://gitlab.com/insanitywholesale/dotfiles/raw/master/kernel/config-qemukvm-4.19.57-gentoo-gentoo-stable
(cd /usr/src/linux && make olddefconfig && make -j2 && make modules_install && make install && genkernel --install initramfs)
curl -o /etc/default/grub https://gitlab.com/insanitywholesale/dotfiles/raw/master/gentoo/grub
#grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=gentoo --removable
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
useradd -m -G audio,video,portage,wheel angle
echo "angle:fail" | chpasswd
echo "root:fail" | chpasswd
echo "exiting chroot"
