#!/bin/bash

git clone https://github.com/endless-sky/endless-sky
cd endless-sky
sudo apt install -y build-essential scons libsdl2-dev libpng-dev libjpeg62-turbo-dev libgl1-mesa-dev libglew-dev libopenal-dev libmad0-dev
scons
./endless-sky
