#!/bin/bash

apt -y install apt-transport-https
add-apt-repository -y universe
wget -O - https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | apt-key -y add -
echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/ubuntu $( lsb_release -c -s ) main" | tee /etc/apt/sources.list.d/jellyfin.list
apt update
apt -y install jellyfin
